### ISSUE TITLE
Confusing error message in calculate tangents if missing UVs

### ISSUE THREAD

**Issue by felixbento22** [ssbucarlos/smash-ultimate-blender#125]
Triangulate Check Error Occurs Even When Faces Are Triangulated. Some sort of bug. Included Example Blender File
[yosuke try3.zip](https://github.com/ssbucarlos/smash-ultimate-blender/files/9155074/yosuke.try3.zip)

**Comment by ScanMountGoat** [comment]
The error message is inaccurate. Meshes are automatically triangulated on export if necessary. The real problem is that the meshes have no UV maps. Each mesh should have at least one UV map to work properly in game. Make sure to rename them to "map1" in the object data properties panel. I'll add a check for this and adjust the error message to make this clearer in the future.

**Comment by ScanMountGoat** [comment]
I've fixed the error message on the latest version. Each mesh should have a UV map like the image below to export properly.
![image](https://user-images.githubusercontent.com/23301691/180105165-f2f812f6-27c4-467f-8147-80b141562f63.png)
