### ISSUE TITLE
Permission Error When Exporting on MacOS

### ISSUE THREAD

**Issue by progenitor7** [ssbucarlos/smash-ultimate-blender#132]
Greetings!

I saw a similar error in issue #63 where a Linux user was unable to export their model due to a permission error due to some coding related to their numshexb. For me the error is slightly different though.

<img width="1051" alt="Screen Shot 2022-08-13 at 6 49 36 PM" src="https://user-images.githubusercontent.com/109327944/184516100-e938daff-4f1f-4f05-a5a5-84936d39960c.png">

**Comment by ScanMountGoat** [comment]
This is related to nuhlpb functionality being windows only for now. See my comments on #129. As a temporary workaround, disable nuhlpb export in the export menu. While not as nice as Blender, you can use ssbh_data_json on MacOS to edit nuhlpb files. You'll need to compile from source since I don't provide ssbh_data_json binaries for MacOS at this time. SSBH Editor can edit existing nuhlpb entries, but you can't add or delete entries yet.

**Comment by progenitor7** [comment]
Perfect thank you!

**Comment by ScanMountGoat** [comment]
This will be fixed once #147 is done. The addon currently won't load on Apple Silicon macs due to a missing library. Older intel macs should work without any issues.

**Comment by ScanMountGoat** [comment]
This is fixed on the latest commit.
