### ISSUE TITLE
'list' object cannot be converted to 'Transform' error when exporting animations

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#173]
The error happens when calling `ssbh_anim_data.save(...)` if the material tracks are included in the export settings.

**Comment by ssbucarlos** [comment]
I tested on a few anims yesterday and didn't get the error, ill test more thoroughly when i get back home and fix it

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: SMG ***@***.***>
Sent: Sunday, November 20, 2022 12:03:07 PM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] 'list' object cannot be converted to 'Transform' error when exporting animations (Issue #173)


The error happens when calling ssbh_data_anim.save(...)

**Comment by ScanMountGoat** [comment]
I tested sonic's c03attacks4s and mario's a00wait2 animations for reference.

**Comment by ssbucarlos** [comment]
thanks im going to take a look at it now

**Comment by ssbucarlos** [comment]
ok it should be fixed now, thanks for testing and letting me know
