### ISSUE TITLE
Remove warnings for more than one UV per vertex

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#175]
The original purpose of these warnings was to notify users that modifications needed to be made to the mesh internally that may result in slight inaccuracies in the export. The latest version preserves the original custom normals using a color attribute and recalculates tangents on export, so there is no longer any advantage to a user manually trying to split or triangulate the model. Removing the warnings should reduce confusion. The wiki page can also be updated to explain that splitting vertices is no longer beneficial since the exporter is more accurate than splitting and using a data transfer modifier.

**Comment by ssbucarlos** [comment]
sorry i didnt respond to this, but i meant to take note that some users occasionally run into export issues or errors. nobody tagged me in the errors so im only now starting to review them. I don't think removing the warning is ready quite yet, since it at leasts hints to the user why there may be issues with export (assuming the issues really are reproducible). i need to compile specific details, but errors include normals still not being correct on export and apparently the workaround some users are doing is to use FBX model export and import to studioSB. Ill let you know as i gather more info

**Comment by ScanMountGoat** [comment]
The latest commit can now export normals for hard edges by splitting the necessary edges on export. It made sense to keep this warning when it was only splitting UV seams. The actual operation that needs to be performed is splitting the vertices to allow per loop attributes to be converted to per vertex attributes on export. The latest commit checks for loop UVs as well as loop normals. It isn't feasible for a user to correctly identify and split the correct edges. Even if the user did manage to split the edges, the user would still need to use an unreliable data transfer modifier.

If people are still experiencing issues with normals, they should submit an issue on github and link the blend to allow us to look into it. There are a lot of weird things that can happen especially with models ripped from other games.

**Comment by ScanMountGoat** [comment]
I'm leaving the warning for non triangular faces since there are usually multiple ways to triangulate the model. It's also much easier for a user to fix manually.
