### ISSUE TITLE
Cannot parent to trans bone, Model ends up floating

### ISSUE THREAD

**Issue by osliecranwave** [ssbucarlos/smash-ultimate-blender#200]
So i was making an exo skel but I figured out I couldn't parent the "trans" bone from the smash armature to the other armature, this leads to the model floating when animations are played 
<img width="405" alt="Skjermbilde 2023-08-04 kl  05 59 43" src="https://github.com/ssbucarlos/smash-ultimate-blender/assets/138881362/765b5fbb-55cf-444c-95e4-9a85b41d3ccb">
<img width="405" alt="Skjermbilde 2023-08-04 kl  05 59 35" src="https://github.com/ssbucarlos/smash-ultimate-blender/assets/138881362/f857dc36-f926-4ce0-922f-6d6ade03adab">
<img width="754" alt="Skjermbilde 2023-08-04 kl  06 08 13" src="https://github.com/ssbucarlos/smash-ultimate-blender/assets/138881362/2c726d4b-9b12-425b-a4ff-35de71d84ee0">
How do I stop the model from floating?

**Comment by ssbucarlos** [comment]
So "parenting" and "pairing" are two different things. Also, Helper bones (which is what the exo plugin is creating) do not copy Translations, only Rotations. You can't pair to the Trans bone since that doesn't rotate, only translates, so pairing would do nothing.
What you need to do is "parent" the root bone of your custom skel to the smash hip bone. This is covered in the exo skel tutorial by cybertron.
https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Tutorials#magic-exoskeleton-tutorial-by-cybertron
