### ISSUE TITLE
Error message with Eye Material Custom

### ISSUE THREAD

**Issue by Nixoup** [ssbucarlos/smash-ultimate-blender#227]
Hello,
When I use the tool to move the pupil of a character, it does not work and this type of message appears:
![Sans titre 1](https://github.com/user-attachments/assets/e51d9f5b-2e2e-4a35-b321-08fcabc1f3e2)

The tool currently only works with Donkey Kong

**Comment by ssbucarlos** [comment]
what character did u get that error on?

**Comment by ssbucarlos** [comment]
Also does it work after you import or create an animation?

**Comment by ssbucarlos** [comment]
![image](https://github.com/user-attachments/assets/4bbf3875-24b0-4dc4-a2a8-17f5b3735f27)

I have pushed an update so now you will get a proper error message instead of that, but basically the eye modal needs an eye material track loaded with the customvector31 property loaded like in the picture i provided

**Comment by Nixoup** [comment]
Hello,
The error occurs on almost all characters. And it only works when an animation is imported.

I updated Blender and your tool. I followed your instructions on the picture but it doesn't work (without importing animation).
How to add "EyeL" and "EyeR" in the list like in your picture? The "+" button only creates a "NewMaterialTrack".

**Comment by ssbucarlos** [comment]
You can rename a track by double clicking on the name. The update i pushed just provides a better error message, so u will still need to create the EyeL or EyeR tracks as needed.
