### ISSUE TITLE
Account for track TransformFlags on import (Sora hair swing bones)

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#75]
The Problem:
![image](https://user-images.githubusercontent.com/77519735/151887048-5ec45983-8104-405a-a6c5-3e8f910fd7b9.png)
This is due to the swing bones containing translation values during the anim of (0,0,0). Typicially, swing bones either contain either 'baked' physics for better looking physics or at the very least they should contain the rest position values of the bone. 

A Workaround:
Currently the user needs to clear out the translation keyframes in blender to make the bone return to its rest position. However this alters export.

Ideas for a fix:
Maybe check for the value of (0,0,0) and replace with the values needed to get the bone to its rest pose position. This would however cause export to not be 1:1, maybe smash expects the (0,0,0) to be there. Maybe put an option on import for this fix, or maybe add a custom bone property to track which bones need to be uncorrected on export. I will need to look more into this later

**Comment by ScanMountGoat** [comment]
If translation is set to (0,0,0) for the entire track, that would save on file sizes due to how the animation compression works. It sounds like the translation is being set from something else, which should be toggled by something. Are there any other examples of this happening?

**Comment by ssbucarlos** [comment]
various pyra and mythra anims have the same behavior. All their victory anims have it. also iirc every fighters 'thrown' anims also have the same behavior.

**Comment by ScanMountGoat** [comment]
This could be related to flags in the anim file. Each track has unresearched flags in the `unk_flags` field. There are also additional flags for compressed tracks that haven't been well researched. The only value for `CompressionFlags` that I've put any significant time into is the `ScaleType`. Changing bits in the `CompressionFlags` and `UnkFlags` seems to affect how the transformation values get used.

If this changes on a per anim basis, it's probably related to the flags. There may also be something set in the swing bone files, but I haven't looked into them much.

**Comment by ScanMountGoat** [comment]
The `unk_flags` are editable with ssbh_lib_json. The compression flags aren't editable without editing the source code for ssbh_data.

**Comment by ssbucarlos** [comment]
Yeah seems like normal swing bones have the unk_flags set to zero, whereas the problematic swing bones + the affected bones in the `thrown` anim have it non-zero.

**Comment by ssbucarlos** [comment]
Btw what are you using to view the CompressionFlags? I tried using ssbh_lib_json but didnt see them there.

**Comment by ScanMountGoat** [comment]
You'll have to put some `dbg!` or `println!` statements in ssbh_data. It's intentionally not part of the public API at the moment since you can't manually set a track as compressed. The relevant code for compressed transforms starts here if you're curious. `data.header.flags` has the `CompressionFlags`. https://github.com/ultimate-research/ssbh_lib/blob/9fcd5773e3089bfcb59988a7ea88ec5da50f928c/ssbh_data/src/anim_data/buffers.rs#L341-L355

**Comment by ssbucarlos** [comment]
ah ok that makes sense why its not part of the api. ty for the info

**Comment by ScanMountGoat** [comment]
I did some testing for the unk_flags. This issue is reproducible on any skeletal animation. I've already updated ssbh_lib, but it will be a while until these changes find their way to ssbh_data_py. I'm still finalizing the wording and API for ssbh_data.

 You can find the changes to ssbh_lib here. Some of the swing bones are using the translation override to use the translation values from the "rest pose". This would be `1` as an integer or `[1,0,0,0]` in ssbh_lib_json.  https://github.com/ultimate-research/ssbh_lib/blob/150e38be83c00b8b9af9016e1a3ab3a63fda8cd5/ssbh_lib/src/formats/anim.rs#L169-L202

**Comment by ScanMountGoat** [comment]
Setting all these flags to true for all bones is an easy way to make a T-pose regardless of the values set for translation, rotation, and scale in the transform values themselves.

**Comment by ssbucarlos** [comment]
Thank you so much for testing the unk_flags, i had no idea that there were seperate overrides. Ill keep an eye out for the update to the ssbh_data_py api so i can properly account for these flags. tyvm again

**Comment by ScanMountGoat** [comment]
This should be relatively simple to implement. The basic idea is to decompose the skeleton transform into its scale, rotation, and translation components. If the transform flags have override_scale set to true, for example, use the scale from the bone transform instead of the transform track. Once it's "baked into" the animation, we won't need to do anything special on export and can leave all the flags set to false. 

The only issue is if people want to animate swing bone or thrown animations in Blender. They could set the flags manually with ssbh_data_json until we figure something out.

**Comment by ScanMountGoat** [comment]
This is implemented on the latest version.
